name: pr-test
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  basic_test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: |
          npm install

      - name: Compile files
        run: |
          npm run build

      - name: Specific version test- Postive
        uses: ./
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az --version

      - name: Latest version test - Postive
        uses: ./
        with:
          azcliversion: latest
          inlineScript: |
            az --version

      - name: Default version test - Postive
        uses: ./
        with:
          inlineScript: |
            az --version

      - name: Invalid Version test - Negative
        id: test1
        continue-on-error: true
        uses: ./
        with:
          azcliversion: 0
          inlineScript: |
            az --version

      - name: Check Last step failed
        if: steps.test1.outcome == 'success'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.setFailed('Last action should fail but not. Please check it.')

      - name: Invalid Script test - Negative
        id: test2
        continue-on-error: true
        uses: ./
        with:
          azcliversion: latest
          inlineScript: " "

      - name: Check Last step failed
        if: steps.test2.outcome == 'success'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.setFailed('Last action should fail but not. Please check it.')

  os_test:
    if: github.actor != 'dependabot[bot]'
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: |
          npm install

      - name: Compile files
        run: |
          npm run build

      - name: Invalid OS - Negative
        id: test3
        continue-on-error: true
        uses: ./
        with:
          azcliversion: latest
          inlineScript: |
            az --version

      - name: Check Last step failed
        if: steps.test3.outcome == 'success'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.setFailed('Last action should fail but not. Please check it.')
